### ISSUE TITLE
How to treat IPN notifications (Paypal)?

### ISSUE THREAD

**Issue by silasrm** [Payum/PayumBundle#266]
How to treat IPN notifications (Paypal)?
The documentation don't say how make this.

**Comment by silasrm** [comment]
I see the IPN history, get the query data and test request to notify_url existed on profile, but nothing happening. Example:
URL: http://host.dev:8084/payment/notify/jueBUncoYtdNoCR1Diips1skrdWWB2GHTWJSXEA1Fw4
Data: mc_gross=300.00&protection_eligibility=Ineligible&item_number1=&payer_id=Z2746Z4ZDZ9JJ&tax=0.00&payment_date=17:39:10 May 01, 2015 PDT&payment_status=Completed&charset=windows-1252&mc_shipping=0.00&mc_handling=0.00&first_name=Silas&mc_fee=10.60&notify_version=3.8&custom=&payer_status=verified&num_cart_items=1&mc_handling1=0.00&verify_sign=AQEgFLG-gYJRPNwVRAb4gD.Dx6t9AmhK350tHkqkn0K6oTY89RukOmSo&payer_email=silasrm+paypalcliente@gmail.com&mc_shipping1=0.00&tax1=0.00&txn_id=6NU11144MU741662Y&payment_type=instant&last_name=Ribas Martins&item_name1=PHP (Assinatura) Upgrade&receiver_email=silasrm+paypal@gmail.com&payment_fee=&quantity1=1&receiver_id=6AQ5JT763PV64&txn_type=cart&mc_gross_1=300.00&mc_currency=BRL&residence_country=BR&test_ipn=1&transaction_subject=PHP (Assinatura) UpgradeUpgrade da assinatura&payment_gross=&ipn_track_id=cb027884e4a34

Return: 
Status 204 No Content

Nothing happens on database.

**Comment by makasim** [comment]
by design you have to add your own action over existing ones. This action let's say YourNotifyAction proxy the request to the Payum and after that checks the payment status. When you have a status you can do whatever your business tells you to do
You can go the other way with extension. Just create Payum's extension and check the status onPostExecute, dispatch events etc.

**Comment by silasrm** [comment]
Ok. Thank's
