### ISSUE TITLE
A use case : payment without credit card info

### ISSUE THREAD

**Issue by videni** [Payum/PayumBundle#299]
After I dug into its source code , I found that the ObtainCreditCardAction action is always executing, which tells me that credit car info is always needed, but my use case varies.
> A user buys a book using Alipay,  he will be redirected to page showing QR code
> he scans that QR code via Alipay app  using his iphone, and confirm
> then the payment is done.

As you can see, credit card info is not required, can anybody give me some clues on this please?

**Comment by makasim** [comment]
Are you using omnipay bridge? If so there are two different gateways

* omnipay_offsite - you have to use this one when the payment requires a redirect
* omnipay_direct - for credit card gateways.

There is no way to abstract this logic due to limitations in omnipay, so you have to explicitly set what gateway you need

**Comment by videni** [comment]
@makasim ,I see,  thank you for telling me this, very appreciate  your help.
