### ISSUE TITLE
Creating a notify token (clarification required)

### ISSUE THREAD

**Issue by KirbyFox** [Payum/PayumBundle#433]
I was reading the following docs page, but it's not entirely clear.

`https://github.com/Payum/PayumBundle/blob/master/Resources/doc/console_commands.md#create-notify-token`

Within a Sylius website, would the command be as follows?

`$ php bin/console payum:security:create-notify-token paypal --model-class=/Sylius/Component/Payment/Model/Payment --model-id=1`

Also, what does the model-id=1 represent please?

If I wanted to generate a notify token for Worldpay, do I simply swap the word 'paypal' with the word 'worldpay' within the above command?

Would is be model-id=1 for all use cases?

Then presumably the resulting URL is entered within the Payment Gateway Account page.

Also, where is the notification token stored please?

**Comment by makasim** [comment]
There are two types of payment providers:

1. support notifications per payment, such as paypal express checkout
2. do not support per payment notifications but a single url for all of them, such as be2bill

Everything is simple for the payment providers of the first group. For the second a workaround needed. You store your real model id or a real notify token in the payment details that you sent to them in order to get them later in the notification request. You extract that data and continue the execution. 

Having that in mind `--model-id=1` means nothing in this case, it mustn't be used. The token is here to add make your notify a bit more protected (a bad guy has to know the token hash in order to accessthe url).

**Comment by makasim** [comment]
If you are dealing with a payment provider from the second group, use be2bill as a reference.

**Comment by KirbyFox** [comment]
Thanks @makasim Yes, I've just built a WorldPay integration and I actually used be2bill as a starting point and it's working well.

I will follow your advice and give that a go.

Many thanks for clarifying that.
