### ISSUE TITLE
this happen after trying to install it

### ISSUE THREAD

**Issue by PaYo90** [Payum/PayumBundle#521]
![image](https://user-images.githubusercontent.com/10090618/99923043-2a876e00-2d34-11eb-91c5-644e3ca76a23.png)

**Comment by Tetragramat** [comment]
Please update your issue with version of payum bundle and symfony you're installing, replace printscreen with output of your command line and be more specific what is your issue.

**Comment by tsdevelopment** [comment]
I have the same problem with Symfony 5.2. The recipe is not more correct. You can change `%kernel.root_dir%` to  `%kernel.project_dir%` in `config/packages/payum.yaml`.

**Comment by pierredup** [comment]
This should be fixed in https://github.com/symfony/recipes-contrib/pull/1085.
Note that PR also changes the default storage location, to be more consistent with the newer versions of Symfony.
This should fix the error for any new projects. For existing projects, you can just change the values in `config/packages/payum.yaml` as suggested by @tsdevelopment.

**Comment by pierredup** [comment]
@PaYo90 @tsdevelopment This should be fixed now with the latest Flex recipe.
