### ISSUE TITLE
Support for Symonfy 6

### ISSUE THREAD

**Issue by Chris53897** [Payum/PayumBundle#539]
Allow Symfony 6.
This PR https://github.com/Payum/PayumBundle/pull/537 already removes some deprecations.

TODO:
* Change composer.json
* Remove all deprecations (DI)
* Switches for Symfony 4 and 5+6
* Dependencies?
* Adjust Testing
* Tests

I already took a quick look and could get an installable set (but not stable releases). https://github.com/Chris53897/PayumBundle/tree/feature/symfony6

It would help the maintainers to drop Support of Symfony 4.
https://symfony.com/releases/4.4
https://symfony.com/releases
WDYT?
As it is still an active LTS i can understand to not drop support yet.

I can take this PR, but i will wait after some PRs of mine are hopefully merged.
At least https://github.com/Payum/PayumBundle/pull/536 for betting Testing.

**Comment by pierredup** [comment]
Since 4.4 is still in active support for the rest of the year (and then 1 year of security fixes after that), I don't think we should drop support for 4.4 now. If possible, we should try and support from 4.4 to 6.0. If that's not possible, then I think we can start working on version 3 of this bundle, which drops Symfony 4 and PHP 7 support, but still keep version 2 in active support for the next year so (effectively meaning that we have both active and supported version 2 and 3 of this bundle)

**Comment by Chris53897** [comment]
I guess it will be possible to support both. But a lot of extra work.
And there are BC breakes, [example](https://github.com/Payum/PayumBundle/pull/537#pullrequestreview-894490652), so a major version makes more sense to me.
I would love to do a PR for version 3 with Php >= 8 and Symfony ^5.4 || ^6.0 Support.

I could start with the PR after my 2 remaining PRs are merged and i have your permission to do this like suggessted.
